# Generated by Django 3.0.3 on 2020-03-15 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('box_id', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('box_type', models.CharField(choices=[('vendor box', 'vendor box'), ('packed box', 'packed box'), ('stocked out', 'stocked out')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'company'), (2, 'individual')], default=1)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('VATnumber', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('deliveryAddress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('sku', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('model_full_name', models.CharField(max_length=255)),
                ('model_short_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='userName')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('admin', models.BooleanField(default=False, verbose_name='admin')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VendorSaleInvoice',
            fields=[
                ('vendor_serial_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pull_number', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale_invoice', models.CharField(default='NA', max_length=255)),
                ('box', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='vendorSaleInvoice_box', to='blog.Box')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_sale', to='blog.Box')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sale', to='blog.Customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sale', to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('serial_id', models.AutoField(primary_key=True, serialize=False)),
                ('hex_number', models.CharField(max_length=255)),
                ('cut_off_id', models.CharField(max_length=255)),
                ('strap', models.CharField(choices=[('Y', 'Y'), ('Y', 'N')], max_length=1)),
                ('FMIP', models.CharField(choices=[('Y', 'Y'), ('Y', 'N')], max_length=1)),
                ('saleprice', models.DecimalField(decimal_places=10, default=0.0, max_digits=12, verbose_name='Low')),
                ('box', models.ForeignKey(db_constraint=False, default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='product_box', to='blog.Box')),
                ('model', models.ForeignKey(db_constraint=False, default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='product_sku', to='blog.Model')),
                ('sale', models.ForeignKey(db_constraint=False, default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='product_sale', to='blog.Sale')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to='blog.User')),
                ('vendor_sale_invoice', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='vendorSaleInvoice_product', to='blog.VendorSaleInvoice')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_box', to='blog.User'),
        ),
    ]
