# Generated by Django 3.0.3 on 2020-03-16 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200316_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='datatime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 7, 13, 45, 891223, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='box',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 7, 13, 45, 889024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 7, 13, 45, 889815, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 7, 13, 45, 862618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vendorsaleinvoice',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 7, 13, 45, 890264, tzinfo=utc)),
        ),
    ]
