# Generated by Django 3.0.3 on 2020-03-16 12:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200316_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='datatime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 20, 58, 49, 696218)),
        ),
        migrations.AlterField(
            model_name='box',
            name='box_type',
            field=models.CharField(choices=[('cuted off', 'cuted off'), ('packed', 'packed'), ('stocked out', 'stocked out'), ('Not in box', 'Not in box')], max_length=255),
        ),
        migrations.AlterField(
            model_name='box',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 20, 58, 49, 694283)),
        ),
        migrations.AlterField(
            model_name='product',
            name='box',
            field=models.ForeignKey(db_constraint=False, default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='product_box', to='blog.Box'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 20, 58, 49, 694960)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 20, 58, 49, 688793)),
        ),
        migrations.AlterField(
            model_name='vendorsaleinvoice',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 20, 58, 49, 695338)),
        ),
    ]
