# Generated by Django 3.0.3 on 2020-03-16 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200316_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='datatime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 23, 13, 41, 401830)),
        ),
        migrations.AlterField(
            model_name='vendorsaleinvoice',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
