# Generated by Django 3.0.3 on 2020-03-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200317_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='customer_sale', to='blog.Customer'),
        ),
    ]
