# Generated by Django 3.0.3 on 2020-03-17 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200317_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='box',
            field=models.ForeignKey(db_constraint=False, default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='box_sale', to='blog.Box'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(db_constraint=False, default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='customer_sale', to='blog.Customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(db_constraint=False, default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='user_sale', to='blog.User'),
        ),
    ]
