# Generated by Django 3.0.3 on 2020-03-17 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200317_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='box',
        ),
        migrations.AddField(
            model_name='box',
            name='sale',
            field=models.ForeignKey(db_constraint=False, default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='box_sale', to='blog.Sale'),
        ),
    ]
