# Generated by Django 3.0.3 on 2020-03-18 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200317_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorsaleinvoice',
            name='box',
        ),
        migrations.AddField(
            model_name='box',
            name='vendor_sale_invoice',
            field=models.ForeignKey(db_constraint=False, default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='box_vendor_sale_invoice', to='blog.VendorSaleInvoice'),
        ),
    ]
